// p96/frontend/src/components/LazyImage.vue
<template>
  <img
    ref="imgRef"
    :src="loaded ? src : placeholder"
    :alt="alt"
    class="lazy-image"
    :class="{ loading: !loaded }"
  />
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'

const props = defineProps<{
  src: string
  alt?: string
  placeholder?: string
}>()

const imgRef = ref<HTMLImageElement>()
const loaded = ref(false)
let observer: IntersectionObserver | null = null

onMounted(() => {
  if ('IntersectionObserver' in window) {
    observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          loadImage()
          observer?.disconnect()
        }
      })
    }, {
      rootMargin: '100px'
    })

    if (imgRef.value) {
      observer.observe(imgRef.value)
    }
  } else {
    loadImage()
  }
})

const loadImage = () => {
  const img = new Image()
  img.onload = () => {
    loaded.value = true
  }
  img.src = props.src
}

onUnmounted(() => {
  observer?.disconnect()
})
</script>

<style scoped lang="scss">
.lazy-image {
  transition: opacity 0.3s ease;
  opacity: 1;

  &.loading {
    opacity: 0.6;
    background: linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%);
    background-size: 200% 100%;
    animation: shimmer 1.5s infinite;
  }
}

@keyframes shimmer {
  0% {
    background-position: -200% 0;
  }
  100% {
    background-position: 200% 0;
  }
}
</style>

// p34/frontend/src/components/LazyImage.tsx
import React, { useState, useEffect, useRef, memo } from 'react'

export interface LazyImageProps {
  src: string
  alt?: string
  placeholder?: string
  className?: string
  width?: number | string
  height?: number | string
  onLoad?: () => void
  onError?: () => void
}

const LazyImage: React.FC<LazyImageProps> = ({
  src,
  alt = '',
  placeholder = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200"%3E%3Crect fill="%23f3f4f6" width="200" height="200"/%3E%3C/svg%3E',
  className = '',
  width,
  height,
  onLoad,
  onError
}) => {
  const [imageSrc, setImageSrc] = useState(placeholder)
  const [isLoaded, setIsLoaded] = useState(false)
  const [isInView, setIsInView] = useState(false)
  const imgRef = useRef<HTMLImageElement>(null)

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsInView(true)
          observer.disconnect()
        }
      },
      {
        rootMargin: '100px 0px',
        threshold: 0.01
      }
    )

    if (imgRef.current) {
      observer.observe(imgRef.current)
    }

    return () => observer.disconnect()
  }, [])

  useEffect(() => {
    if (isInView && imageSrc === placeholder) {
      const img = new Image()
      img.onload = () => {
        setImageSrc(src)
        setIsLoaded(true)
        onLoad?.()
      }
      img.onerror = () => {
        setImageSrc(placeholder)
        onError?.()
      }
      img.src = src
    }
  }, [isInView, src, placeholder, imageSrc, onLoad, onError])

  return (
    <img
      ref={imgRef}
      src={imageSrc}
      alt={alt}
      className={`${className} transition-opacity duration-300 ${isLoaded ? 'opacity-100' : 'opacity-60'}`}
      style={{ width, height }}
      loading="lazy"
    />
  )
}

export default memo(LazyImage)
